(define (seconds->duration sec) sec)
(define (fork-thread thunk)
  (thread-start! (make-thread thunk)))
(define (sleep duration)
  (thread-sleep! (add-duration (current-time) duration))
  duration)
(define (add-duration time duration)
  (seconds->time (+ (time->seconds time) duration)))
(define (time<? time1 time2)
  (< (time->seconds time1)(time->seconds time2)))
(define (test . args)
  (display "args=")
  (display args)
  (newline)
  )
;; (apply main-proc (cons (program-name)(command-line-arguments)))

(define (current-thread-specific)
  (thread-specific (current-thread))
  )
(define (current-thread-specific-set! value)
  (thread-specific-set! (current-thread) value)
  )
(define (make-eqv-hashtable)
  (make-hash-table eqv?))
(define (hash-table-ref/key table key)
  (hash-table-ref/default table key key))
