(define (make-eqv-hashtable)(make-table test: eqv?))
(define (hash-table-ref/key table key)
  (table-ref table key key))
(define hash-table-set! table-set!)
(define (seconds->duration sec) sec)
(define (add-duration time duration)
  (seconds->time (+ (time->seconds time) duration)))
(define (time<? time1 time2)
  (< (time->seconds time1)(time->seconds time2)))
(define sleep thread-sleep!)
(define (fork-thread thunk)
  (thread-start! (make-thread thunk)))

(define (current-thread-specific)
  (thread-specific (current-thread))
  )
(define (current-thread-specific-set! value)
  (thread-specific-set! (current-thread) value)
  )
