;; (import (rnrs (6)))
;; (import (rnrs (6))(srfi :18)(srfi :19)(srfi :69)); (ice-9 threads))
;; (import (rnrs (6))(srfi :9)(srfi :18)(srfi :69)); (ice-9 threads))
(import (rnrs hashtables (6))(srfi :9)(srfi :18)(srfi :69)); (ice-9 threads))
;; (import (rnrs (6))(srfi srfi-19)(srfi srfi-69))
;; (use-modules (srfi srfi-19)(srfi srfi-69))
(define make-hash-table make-eqv-hashtable)
(define hash-table-ref/default hashtable-ref)
(define hash-table-set! hashtable-set!)
(define (seconds->duration sec) sec)
#; (define (seconds->duration sec)
  (let ((s (floor sec)))
    (let ((ns (- sec s)))
      (set! s (real->flonum s))
      (set! ns (real->flonum (* ns 1000000000)))
      (make-time 'time-duration ns s)
      )
    )
  )
#; (define (seconds->duration sec)
  (let ((s (floor sec)))
    (let ((ns (- sec s)))
      (set! ns (floor (* ns 1000000000)))
      (make-time 'time-duration ns s)
      )
    )
  )
(define (fork-thread thunk)
  (thread-start! (make-thread thunk)))
(define (add-duration time duration)
  (seconds->time (+ (time->seconds time) duration)))
(define (sleep duration)
  ;; (println "sec=" (time->seconds (current-time)))
  (thread-sleep! (add-duration (current-time) duration)))
(define (time<? time1 time2)
  (< (time->seconds time1)(time->seconds time2)))

(define (current-thread-specific)
  (thread-specific (current-thread))
  )
(define (current-thread-specific-set! value)
  (thread-specific-set! (current-thread) value)
  )

(define (hash-table-ref/key table key)
  (hash-table-ref/default table key key))

(define (x->string x)
  (if (string? x) x (object->string x)))

(define (make-queue)
  (cons '( ) '( )))
(define (queue-empty? queue)
  (null? (car queue)))
(define (queue-first queue)
  (let ((first (car queue)))
    (if (null? first) '( )
      (car first))))
(define (queue-add! queue el)
  (let ((first (car queue))(last (cdr queue))(new-last (cons el '( ))))
    (if (null? first)
      (set-car! queue new-last)
      (set-cdr! last new-last))
    (set-cdr! queue new-last)
    (null? first) ; 削除予定
    )
  )
(define (queue-remove! queue)
  (let ((first (car queue)))
    (if (null? first)
      '( )
      (begin
	(set-car! queue (cdr first))
	(car first)))
    )
  )

(define-macro (define-type Name . Fields)
  (cons 'define-record-type
    (cons Name
      (cons
	(cons (string->symbol (string-append "make-" (symbol->string Name)))
	  Fields)
	(cons (string->symbol (string-append (symbol->string Name) "?"))
	  (map (lambda (field)
		 (list field
		   (string->symbol
		     (string-append (symbol->string Name) "-"
		       (symbol->string field)))
		   (string->symbol
		     (string-append (symbol->string Name) "-"
		       (symbol->string field) "-set!")))) Fields)))))
  )
